version: '3.8'

services:
  webapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/src/app/src
    
  database:
    image: 'postgres'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  db-data:
  pgadmin-data:
